{{- $service_name := .Values.service_name -}}
{{- $namespace := .Values.namespace -}}
{{- range .Values.containers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $service_name }}-{{ .name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $service_name }}
type: Opaque
data:
  {{- range .env_vars }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
