apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.namespace }}
data:
  default.conf: |-
    upstream app {
        server 127.0.0.1:{{ .Values.service.main_port }};
    }

    server {
      listen 80 default_server;
      listen [::]:80 default_server;
        
        # Default to go to the app
      location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
      }
    }
        
