apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
    # For all options: https://www.openpolicyagent.org/docs/latest/configuration/

    services:
      splash:
        url: https://splash-rbac-policies.s3.amazonaws.com/{{ .Values.env }}/v1
        credentials:
          s3_signing:
            environment_credentials: {}

    bundles:
      policies:
        service: splash
        resource: api/bundles.tar.gz
        polling:
          min_delay_seconds: 60
          max_delay_seconds: 120

    decision_logs:
      service: splash
      # Enable decision logs to output along with regular container 
      # stdout/stderr logs.
      # Docs: https://www.openpolicyagent.org/docs/latest/configuration/#decision-logs
      console: true
      reporting:
        min_delay_seconds: 300
        max_delay_seconds: 600

