apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service_name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.service_name }}-api-port-http
    port: 80
    protocol: TCP
  {{- if .Values.has_opa }}
  - name: {{ .Values.service_name }}-opa-port-https
    port: 8181
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.service_name }}
