apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
{{- if .Values.has_rbac }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["", "extensions", "apps", "services"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Values.service_name }}-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.service_name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["", "extensions", "apps", "services"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.service_name }}-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.service_name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
