dependencies:
- name: splunk-kubernetes-logging
  version: 1.3.0
  repository: "file://../splunk-kubernetes-logging"
  condition: logging.enabled
- name: splunk-kubernetes-objects
  version: 1.3.0
  repository: "file://../splunk-kubernetes-objects"
  condition: objects.enabled
- name: splunk-kubernetes-metrics
  version: 1.3.0
  repository: "file://../splunk-kubernetes-metrics"
  condition: metrics.enabled
