# Splunk Connect for Kubernetes is a umbraller chart which itself does not contain any template,
# so there is no configurable parameters for itself.

# Use global configurations for shared configurations between sub-charts.
# Supported global configurations:
#
global:
  logLevel: info
  kubernetes:
    clusterName: "oms-dev"
    insecureSSL: true
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
  objects:
    core:
      v1:
        - name: pods
          interval: 30s
        - name: namespaces
          interval: 30s
        - name: nodes
          interval: 30s
        - name: services
          interval: 30s
        - name: config_maps
          interval: 30s
        - name: secrets
          interval: 30s
        - name: persistent_volumes
          interval: 30s
        - name: service_accounts
          interval: 30s
        - name: persistent_volume_claims
          interval: 30s
        - name: resource_quotas
          interval: 30s
        - name: component_statuses
          interval: 30s
        - name: events
          mode: watch
    apps:
      v1:
        - name: deployments
          interval: 30s
        - name: daemon_sets
          interval: 30s
        - name: replica_sets
          interval: 30s
        - name: stateful_sets
          interval: 30s
  splunk:
    hec:
      token: 8f16f9ba-6734-4623-a7e0-1eed5fc2b5bf
      host: lxspisnetqas001
      port: 8088
      indexName: oms_kube_objects
      insecureSSL: true
      protocol: http
splunk-kubernetes-logging:
  rbac:
    create: true
  serviceAccount:
    create: true  
  splunk:
    hec:
      token: 7dcde8aa-9b9f-4158-b1fd-0962204a029f
      host: lxspfmgrqas001
      port: 8088
      insecureSSL: true
      protocol: https
      indexRouting: true
      indexRoutingDefaultIndex:
      #indexName: oms
splunk-kubernetes-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
  kubernetes: 
    kubeletPort: 10250
    useRestClientSSL: true
    insecureSSL: true
  buffer:
    chunk_limit_records: 10000
  aggregatorBuffer:
    chunk_limit_records: 10000  
  splunk:
    hec:
      token: d4ac958f-c58d-486e-acc0-e6c0f0534cb2
      host: lxspisnetqas001
      port: 8088
      insecureSSL: true
      protocol: http
      indexName: oms_metrics
# For other configurations for sub-charts, please check their values.yaml for details.
## Enabling logging will install the `splunk-kubernetes-logging` chart to a kubernetes
## cluster to collect logs generated in the cluster to a Splunk indexer/indexer cluster.
logging:
  enabled: true

## Enabling objects will install the `splunk-kubernetes-objects` chart to a kubernetes
## cluster to collect kubernetes objects in the cluster to a Splunk indexer/indexer cluster.
objects:
  enabled: false

## Enabling metrics will install the `splunk-kubernetes-metrics` chart to a kubernetes
## cluster to collect metrics of the cluster to a Splunk indexer/indexer cluster.
metrics:
  enabled: false
