# This configs KinD to spin up a k8s cluster with trustworthy jwt (Service Account Token Volume Projection) feature.
# This also enables serverside dry run support
# This must be used for 1.12 k8s versions
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1alpha3
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServerExtraArgs:
      "feature-gates": "DryRun=true"
      "service-account-issuer": "kubernetes.default.svc"
      "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
      "service-account-api-audiences": "kubernetes.default.svc"
